Ext.define('SenchaExample.view.grid.complex.agGrid', {
    extend: 'Ext.grid.Grid',
    xtype: 'complexaggrid',
    controller: 'complexgridcontroller',

    requires: [
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.filters.Plugin',
        'Ext.grid.plugin.ViewOptions',
        'Ext.grid.plugin.PagingToolbar',
        'Ext.grid.plugin.SummaryRow',
        'Ext.grid.plugin.Exporter'
    ],

        store: {
        model: 'SenchaExample.model.Agents', // Use the Agents model
        autoLoad: true,
        pageSize: 50, // Enable paging with 50 records per page
        proxy: {
            type: 'ajax',
            url: 'http://localhost:3000/agents', // Mock server endpoint
            reader: {
                type: 'json',
                rootProperty: 'agents' // Matches the "agents" array in agdb.json
            }
        }
    },

    columns: [
        { text: 'Agent ID', dataIndex: 'agentId', width: 100, sortable: true, filter: 'string', tooltip: 'Unique ID of the agent' },
        { text: 'Name', dataIndex: 'name', flex: 1, sortable: true, filter: 'string', tooltip: 'Full name of the agent' },
        { text: 'Email', dataIndex: 'email', flex: 1, sortable: true, filter: 'string', tooltip: 'Email address of the agent' },
        { text: 'Region', dataIndex: 'region', width: 150, sortable: true, filter: 'list', tooltip: 'Region where the agent operates' },
        { text: 'Bookings', dataIndex: 'bookings', width: 100, align: 'center', sortable: true, filter: 'number', tooltip: 'Number of bookings made by the agent' },
        { text: 'Revenue ($)', dataIndex: 'revenue', width: 120, align: 'right', formatter: 'usMoney', sortable: true, filter: 'number', tooltip: 'Total revenue generated by the agent' },
        { text: 'Rating', dataIndex: 'rating', width: 80, align: 'center', sortable: true, filter: 'number', tooltip: 'Performance rating of the agent' },
        { text: 'Join Date', dataIndex: 'joinDate', width: 120, align: 'center', sortable: true, filter: 'date', tooltip: 'Date the agent joined the company' },
        { text: 'Active', dataIndex: 'active', width: 80, align: 'center', xtype: 'checkcolumn', sortable: true, tooltip: 'Whether the agent is currently active' },
        { text: 'Company', dataIndex: 'company', width: 150, sortable: true, filter: 'string', tooltip: 'Company the agent works for' }
    ],

    plugins: {
        cellediting: true,
        gridfilters: true,
        gridviewoptions: true,
        gridexporter: true
    },

    bbar: {
        xtype: 'pagingtoolbar',
        displayInfo: true
    }
});